# Site + Plant Parameters
site:
  depth: 500
  distance: 100
  distance_to_landfall: 100
plant:
  layout: ring
  num_turbines: 50
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
port:
  monthly_rate: 2000000.0
  sub_assembly_lines: 1
  turbine_assembly_cranes: 1
# Vessels
array_cable_install_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
mooring_install_vessel: example_support_vessel
oss_install_vessel: floating_heavy_lift_vessel
support_vessel: example_support_vessel
towing_vessel: example_towing_vessel
towing_vessel_groups:
  station_keeping_vessels: 2
  towing_vessels: 3
wtiv: floating_heavy_lift_vessel
# Module Specific
substructure:
  takt_time: 168
array_system:
  free_cable_length: 0.5
array_system_design:
  cables:
  - XLPE_630mm_66kV
export_system_design:
  cables: XLPE_500mm_132kV
  percent_added_length: 0.0
# Configured Phases
design_phases:
- ArraySystemDesign
- ExportSystemDesign
- SemiTautMooringSystemDesign
# OffshoreFloatingSubstationDesign takes the mooring system unit cost of SemiTautMooringSystemDesign, so that needs to be run first
- OffshoreFloatingSubstationDesign 
- SemiSubmersibleDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MooredSubInstallation: 0
  MooringSystemInstallation: 0
  FloatingSubstationInstallation: 0
  #TurbineInstallation: 0 # We assume the turbine is installed at quayside onto the substructure so the necessary steps are in 'MooredSubInstallation'
# Project Inputs
turbine: 12MW_generic
